GET http://localhost:3002/drivers

###
POST http://localhost:3002/drivers
Content-Type: application/json

{
    "name": "Oscar Piastri",
    "team": "Mclaren",
    "country": "Australia",
    "podiums": 18,
    "image": "piastri.jpg"
}

###
PUT http://localhost:3002/drivers/684a2983e5f3fb3caf6f408e/votes
Content-Type: application/json

###
DELETE http://localhost:3002/drivers/68536f3498bf797f0bdb35bf

###
POST http://localhost:3002/users/register
Content-Type: application/json

{
        "fullname": "Deepali Kadway",
        "contact": "+167876",
        "email": "d1p@gmail.commm",
        "username": "d1eepali_k_adway",
        "password": "dp1@1233"       
}

###
POST http://localhost:3002/users/login
Content-Type: application/json

{
    "username": "deepali_kadway",
    "password": "dp@123"
}